# Generated by Django 5.0.6 on 2025-07-14 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0011_alter_qrdata_desbaste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrdata',
            name='fio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.fio'),
        ),
        migrations.AlterField(
            model_name='qrdata',
            name='polimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.polimento'),
        ),
    ]
