# Generated by Django 5.0.6 on 2025-07-15 13:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0019_rename_desbastecalibre_desbastecalibreworker_desbaste_calibre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrdata',
            name='afinacao',
        ),
        migrations.RemoveField(
            model_name='qrdata',
            name='desbaste_agulha',
        ),
        migrations.RemoveField(
            model_name='qrdata',
            name='desbaste_calibre',
        ),
        migrations.RemoveField(
            model_name='qrdata',
            name='diameter',
        ),
        migrations.RemoveField(
            model_name='qrdata',
            name='die',
        ),
        migrations.RemoveField(
            model_name='qrdata',
            name='job',
        ),
        migrations.RemoveField(
            model_name='qrdata',
            name='polimento',
        ),
        migrations.CreateModel(
            name='dieInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(unique=True)),
                ('diam_desbastado', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('diam_requerido', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('afinacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.afinacao')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='die_instances', to='theme.qrdata')),
                ('desbaste_agulha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.desbasteagulha')),
                ('desbaste_calibre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.desbastecalibre')),
                ('diam_max_min', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='die_instances_max_min', to='theme.diameters')),
                ('diameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='die_instances', to='theme.diameters')),
                ('die', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='theme.die')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='die_instances', to='theme.jobs')),
                ('polimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.polimento')),
                ('tolerance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='die_instances', to='theme.tolerance')),
            ],
        ),
    ]
