# Generated by Django 5.0.6 on 2025-07-15 15:36

import theme.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0023_alter_dieinstance_tolerance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diameters',
            name='max',
            field=theme.models.FlexibleDecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='diameters',
            name='min',
            field=theme.models.FlexibleDecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='dieinstance',
            name='diam_desbastado',
            field=theme.models.FlexibleDecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='dieinstance',
            name='diam_requerido',
            field=theme.models.FlexibleDecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tolerance',
            name='max',
            field=theme.models.FlexibleDecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='tolerance',
            name='min',
            field=theme.models.FlexibleDecimalField(decimal_places=4, max_digits=6),
        ),
    ]
