# Generated by Django 5.0.6 on 2025-07-16 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0025_afinacaoworker_die_instance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afinacaoworker',
            name='die_instance',
        ),
        migrations.RemoveField(
            model_name='desbastecalibreworker',
            name='die_instance',
        ),
        migrations.RemoveField(
            model_name='dieinstance',
            name='afinacao',
        ),
        migrations.RemoveField(
            model_name='dieinstance',
            name='desbaste_agulha',
        ),
        migrations.RemoveField(
            model_name='dieinstance',
            name='desbaste_calibre',
        ),
        migrations.RemoveField(
            model_name='dieinstance',
            name='polimento',
        ),
        migrations.RemoveField(
            model_name='polimentoworker',
            name='die_instance',
        ),
        migrations.CreateModel(
            name='DieWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_type', models.CharField(choices=[('polimento', 'Polimento'), ('desbaste_agulha', 'Desbaste Agulha'), ('desbaste_calibre', 'Desbaste Calibre'), ('afinacao', 'Afinação')], max_length=20)),
                ('subtype', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('die', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='theme.dieinstance')),
            ],
        ),
        migrations.CreateModel(
            name='DieWorkWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workers', to='theme.diework')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
