# Generated by Django 5.0.6 on 2025-08-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0037_pedidosdiametro_pedido_por'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosdiametro',
            name='serie_dies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
