# Generated by Django 5.0.6 on 2025-08-07 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0039_numeropartidos_serie_dies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='numeropartidos',
            old_name='serie_dies',
            new_name='serie_dies_partidos',
        ),
    ]
