# Generated by Django 5.2.5 on 2025-08-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0055_order_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderscoming',
            name='preshipment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='plant',
            field=models.CharField(blank=True, choices=[('P2', 'P2'), ('P3', 'P3'), ('Toma', 'Toma')], max_length=6, null=True),
        ),
    ]
