from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', views.home, name='home'),
    path('create-user/', views.create_user, name='create_user'),
    path('login/<int:user_id>/', views.login_view, name='login'),
    path('erro403/', views.erro403, name='erro403'),
    path('mainMenu/<int:user_id>/', views.mainMenu, name='mainMenu'),
    path('inputProduction/', views.inputProduction, name='inputProduction'),
    path('editProduct/<int:produto_id>/', views.editProduct, name='editProduct'),
    path('delectProduct/<int:produto_id>/', views.deleteProduct, name='delectProduct'),
    # path('scanBox/', views.scanBox, name='scanBox'),
    path('listQrcodes/', views.listQrcodes, name='listQrcodes'),
    path('edit-qr-inline/<int:qr_id>/', views.edit_qr_inline, name='edit_qr_inline'),
    path('partidosMenu/<path:toma_order_full>/', views.partidosMenu, name='partidosMenu'),
    path('diametroMenu/<path:toma_order_full>/', views.diametroMenu, name='diametroMenu'),
    path('qrdata/editar/<int:qr_id>/', views.showDetails, name='showDetails'),
    path('infoFieira/<int:die_id>/', views.info_fieira, name='infoFieira'),
    path('qrcode/<int:qr_id>/dies/', views.adicionar_dies, name='adicionar_dies'),
    path('dies/', views.listar_qrcodes_com_dies, name='listarDies'),
    path('die/<int:die_id>/', views.die_details, name='die_details'),
    path('die/<int:die_id>/novo-trabalho/', views.create_die_work, name='create_die_work'),
    path('die-work/<int:work_id>/add-worker/', views.add_worker_to_die_work, name='add_worker_to_die_work'),
    path('die/work/workers/<int:qr_id>/', views.add_multiple_works_workers, name='add_multiple_works_workers'),
    path('qrcode/<int:qr_id>/export-excel/', views.export_qrcode_excel, name='export_qrcode_excel'),
    path('enviar-fieira/<int:die_id>/', views.enviar_fieira, name='enviar_fieira'),
    path('enviar-caixa/<int:qr_id>/', views.enviar_caixa, name='enviar_caixa'),
    path('fieira_path/', views.fieira_path, name='fieira_path'),
    path('create-caixa/', views.create_caixa, name='create_caixa'),
    path('listarPedidosDiametro/', views.listarPedidosDiametro, name='listarPedidosDiametro'),
    path('pedidos/diametro/editar/<int:id>/', views.editar_pedido_inline, name='editar_pedido_inline'),
    path('pedidos/diametro/excel/<int:id>/', views.exportar_pedido_excel, name='exportar_pedido_excel'),   
    path('listarPartidos/', views.listarPartidos, name='listarPartidos'),
    path('localizarFieira/', views.localizarFieira, name='localizarFieira'),
    path('qOfficeMenu/', views.qOfficeMenu, name='qOfficeMenu'),
    path('productionMenu/', views.productionMenu, name='productionMenu'),
    path('comercialMenu/', views.comercialMenu, name='comercialMenu'),
    path('partidos/<int:pk>/toggle-feito-ajax/', views.toggle_partido_feito_ajax, name='toggle_partido_feito_ajax'),
    path('pedidos/<int:pk>/toggle-feito-ajax/', views.toggle_pedido_diametro_feito_ajax, name='toggle_pedido_diametro_feito_ajax'),
    path('deliveryIdentification/<path:toma_order_full>/', views.deliveryIdentification, name='deliveryIdentification'),
    path('delivery/calendar/', views.deliveryCalendar, name='deliveryCalendar'),
    path('listarInfo/', views.listarInfo, name='listarInfo'),
    path('deletarDelivery/<int:id>/', views.deletar_delivery, name='deletar_delivery'),
    path('logout/', views.user_logout, name='logout'),
    path('orders/', views.orders, name='orders'),
    path('orders/listar/', views.listar_orders, name='listarOrders'),  
    path('orders/<int:order_id>/edit/', views.edit_order, name='editOrder'),
    path('orders/<int:order_id>/delete/', views.delete_order, name='deleteOrder'),
    path('orders/file/<int:file_id>/delete/', views.delete_order_file, name='deleteOrderFile'),
    path('orders/create_orders_coming_ajax/', views.create_orders_coming_ajax, name='create_orders_coming_ajax'),
    path('orders/coming/<int:oc_id>/edit/', views.edit_orders_coming, name='editOrdersComing'),
    path('administrationMenu/', views.administrationMenu, name='administrationMenu'),
    path('orders/<int:order_id>/export-excel/', views.exportOrderExcel, name='exportOrderExcel'),
    path('adicionarTracking/', views.create_tracking, name='adicionarTracking'),
    path('listarTracking/', views.listar_trackings, name='listarTracking'),
    path('editarTracking/<int:pk>/', views.create_tracking, name='editarTracking'),
    path('listarMedicoes/', views.listar_medicoes, name='listarMedicoes'),
    path('listarCalibracoes/', views.listar_calibracoes, name='listarCalibracoes'),
    path('charts/', views.charts, name='production_chart'),
    path('listarFaturas/', views.listarFaturas, name='listarFaturas'),
    path('criarFatura/', views.criarFatura, name='criarFatura'),
    path('editar_fatura/<int:fatura_id>/', views.editarFatura, name='editarFatura'),
    path('api/upload-fatura/', views.upload_arquivo_fatura, name='api_upload_fatura'),
    path('api/delete-anexo/', views.delete_anexo_api, name='api_delete_anexo'),
    path('menuFinanceiro/', views.financeiroMenu, name='financeiroMenu'),
    path('listarFornecedores/', views.listarFornecedores, name='listarFornecedores'),
    path('atualizar-fornecedor/<int:id>/', views.atualizar_fornecedor, name='atualizar_fornecedor'),
    path('deletar-fornecedor/<int:id>/', views.deletar_fornecedor, name='deletar_fornecedor'),
    path('templateFiles/', views.templateFiles, name='templateFiles'),
    path('upload-template-file/<int:id>/', views.upload_template_file, name='upload_template_file'),
    path('criarTemplate/', views.criarTemplate, name='criarTemplate'),
    path('editarTemplate/<int:id>/', views.editarTemplate, name='editarTemplate'),
    path('delete-file/<int:file_id>/', views.delete_template_file, name='delete_template_file'),
]
handler403 = 'theme.views.erro403'
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)