# Generated by Django 5.0.6 on 2025-07-09 13:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_productdeletelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('customer_order_nr', models.CharField(max_length=50)),
                ('toma_order_nr', models.CharField(max_length=50)),
                ('toma_order_year', models.CharField(max_length=10)),
                ('box_nr', models.IntegerField()),
                ('qt', models.IntegerField()),
                ('diameters', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
