# Generated by Django 5.0.6 on 2025-07-11 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0004_qrdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(choices=[('F', 'Furação'), ('R', 'Ranhura'), ('P', 'Polimento'), ('W', 'Soldadura'), ('N', 'Nenhum'), ('ND', 'Não definido')], max_length=2, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='qrdata',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.jobs'),
        ),
    ]
