# Generated by Django 5.0.6 on 2025-07-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0005_jobs_qrdata_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job',
            field=models.CharField(choices=[('F', 'Final'), ('R', 'Recondicionado'), ('P', 'Polimento'), ('W', 'Com o mesmo diametro(W)'), ('N', 'Novo'), ('ND', 'Diamante Natural')], max_length=2, unique=True),
        ),
    ]
