# Generated by Django 5.0.6 on 2025-07-11 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0006_alter_jobs_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Desbaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('cone', 'Cone')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Diameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Die',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('die_type', models.CharField(choices=[('ND', 'Diamante Natural'), ('PCD', 'Policristalino'), ('MCD', 'Monocristalino')], max_length=3, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tolerance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='qrdata',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job',
            field=models.CharField(choices=[('F', 'Final'), ('R', 'Recondicionado'), ('P', 'Polimento'), ('W', 'Com o mesmo diametro(W)'), ('N', 'Novo')], max_length=1, unique=True),
        ),
        migrations.CreateModel(
            name='DesbasteWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('desbaste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.desbaste')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='desbaste',
            name='workers',
            field=models.ManyToManyField(through='theme.DesbasteWorker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='qrdata',
            name='desbaste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.desbasteworker'),
        ),
        migrations.AddField(
            model_name='qrdata',
            name='diameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.diameters'),
        ),
        migrations.AddField(
            model_name='qrdata',
            name='die',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.die'),
        ),
        migrations.AddField(
            model_name='qrdata',
            name='tolerance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.tolerance'),
        ),
    ]
