# Generated by Django 5.0.6 on 2025-07-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0007_desbaste_diameters_die_tolerance_worker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diameters',
            name='max',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='diameters',
            name='min',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='tolerance',
            name='max',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='tolerance',
            name='min',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
    ]
