# Generated by Django 5.0.6 on 2025-07-11 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0008_alter_diameters_max_alter_diameters_min_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('cone', 'Cone')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Polimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('cone', 'Cone')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='FioWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('Fio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.fio')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fio',
            name='workers',
            field=models.ManyToManyField(through='theme.FioWorker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PolimentoWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('polimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.polimento')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='polimento',
            name='workers',
            field=models.ManyToManyField(through='theme.PolimentoWorker', to=settings.AUTH_USER_MODEL),
        ),
    ]
