# Generated by Django 5.0.6 on 2025-07-11 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0009_fio_polimento_fioworker_fio_workers_polimentoworker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrdata',
            name='fio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.fioworker'),
        ),
        migrations.AddField(
            model_name='qrdata',
            name='polimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.polimentoworker'),
        ),
    ]
