# Generated by Django 5.0.6 on 2025-07-11 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0010_qrdata_fio_qrdata_polimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrdata',
            name='desbaste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.desbaste'),
        ),
    ]
