# Generated by Django 5.0.6 on 2025-07-14 08:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0012_alter_qrdata_fio_alter_qrdata_polimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='numeroPartidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partido', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.qrdata')),
            ],
        ),
    ]
