# Generated by Django 5.0.6 on 2025-07-14 08:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0013_numeropartidos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidosDiametro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diametro', models.CharField(max_length=50)),
                ('numero_fieiras', models.IntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('qr_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.qrdata')),
            ],
        ),
    ]
