# Generated by Django 5.0.6 on 2025-07-14 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0014_pedidosdiametro'),
    ]

    operations = [
        migrations.AddField(
            model_name='desbaste',
            name='qr_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='desbastes', to='theme.qrdata'),
        ),
        migrations.AddField(
            model_name='fio',
            name='qr_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fios', to='theme.qrdata'),
        ),
        migrations.AddField(
            model_name='polimento',
            name='qr_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polimentos', to='theme.qrdata'),
        ),
    ]
