# Generated by Django 5.0.6 on 2025-07-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0015_desbaste_qr_code_fio_qr_code_polimento_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fio',
            name='tipo',
            field=models.CharField(choices=[('calibre', 'Calibre'), ('desbaste De Calibre', 'Desbaste de Calibre'), ('afinacao', 'Afinação')], max_length=20),
        ),
    ]
