# Generated by Django 5.0.6 on 2025-07-14 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0016_alter_fio_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desbasteworker',
            name='desbaste',
        ),
        migrations.RemoveField(
            model_name='qrdata',
            name='desbaste',
        ),
        migrations.RemoveField(
            model_name='desbasteworker',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='fio',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='fio',
            name='workers',
        ),
        migrations.RemoveField(
            model_name='fioworker',
            name='Fio',
        ),
        migrations.RemoveField(
            model_name='qrdata',
            name='fio',
        ),
        migrations.RemoveField(
            model_name='fioworker',
            name='worker',
        ),
        migrations.CreateModel(
            name='Afinacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('calibre', 'Calibre'), ('afinacao', 'Afinação')], max_length=20)),
                ('qr_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Afinacoes', to='theme.qrdata')),
            ],
        ),
        migrations.AddField(
            model_name='qrdata',
            name='afinacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.afinacao'),
        ),
        migrations.CreateModel(
            name='AfinacaoWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('Afinacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.afinacao')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='afinacao',
            name='workers',
            field=models.ManyToManyField(through='theme.AfinacaoWorker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DesbasteAgulha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('saida', 'Saída'), ('cone', 'Cone')], max_length=20)),
                ('qr_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DesbasteAgulhas', to='theme.qrdata')),
            ],
        ),
        migrations.AddField(
            model_name='qrdata',
            name='desbasteAgulha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.desbasteagulha'),
        ),
        migrations.CreateModel(
            name='DesbasteAgulhaWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('DesbasteAgulha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.desbasteagulha')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='desbasteagulha',
            name='workers',
            field=models.ManyToManyField(through='theme.DesbasteAgulhaWorker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DesbasteCalibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('polimento De Calibre', 'Polimento de Calibre'), ('desbaste De Calibre', 'Desbaste de Calibre')], max_length=20)),
                ('qr_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='DesbasteCalibres', to='theme.qrdata')),
            ],
        ),
        migrations.AddField(
            model_name='qrdata',
            name='desbasteCalibre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.desbastecalibre'),
        ),
        migrations.CreateModel(
            name='DesbasteCalibreWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('DesbasteCalibre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theme.desbastecalibre')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='desbastecalibre',
            name='workers',
            field=models.ManyToManyField(through='theme.DesbasteCalibreWorker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Desbaste',
        ),
        migrations.DeleteModel(
            name='DesbasteWorker',
        ),
        migrations.DeleteModel(
            name='Fio',
        ),
        migrations.DeleteModel(
            name='FioWorker',
        ),
    ]
