# Generated by Django 5.0.6 on 2025-07-15 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0018_rename_afinacao_afinacaoworker_afinacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desbastecalibreworker',
            old_name='desbasteCalibre',
            new_name='desbaste_calibre',
        ),
    ]
