# Generated by Django 5.0.6 on 2025-07-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0020_remove_qrdata_afinacao_remove_qrdata_desbaste_agulha_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dieinstance',
            name='diameter',
        ),
        migrations.AddField(
            model_name='dieinstance',
            name='diameter_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dieinstance',
            name='serial_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
