# Generated by Django 5.0.6 on 2025-07-15 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0021_remove_dieinstance_diameter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dieinstance',
            name='diam_max_min',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='die_instances_max_min', to='theme.diameters'),
        ),
    ]
