# Generated by Django 5.0.6 on 2025-07-15 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0022_alter_dieinstance_diam_max_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dieinstance',
            name='tolerance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='die_instances', to='theme.tolerance'),
        ),
    ]
