# Generated by Django 5.0.6 on 2025-07-15 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0024_alter_diameters_max_alter_diameters_min_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='afinacaoworker',
            name='die_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theme.dieinstance'),
        ),
        migrations.AddField(
            model_name='desbasteagulhaworker',
            name='die_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theme.dieinstance'),
        ),
        migrations.AddField(
            model_name='desbastecalibreworker',
            name='die_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theme.dieinstance'),
        ),
        migrations.AddField(
            model_name='polimentoworker',
            name='die_instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theme.dieinstance'),
        ),
    ]
