# Generated by Django 5.0.6 on 2025-07-16 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0026_remove_afinacaoworker_die_instance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='afinacao',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='afinacao',
            name='workers',
        ),
        migrations.RemoveField(
            model_name='afinacaoworker',
            name='afinacao',
        ),
        migrations.RemoveField(
            model_name='afinacaoworker',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='desbasteagulha',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='desbasteagulha',
            name='workers',
        ),
        migrations.RemoveField(
            model_name='desbasteagulhaworker',
            name='desbaste_agulha',
        ),
        migrations.RemoveField(
            model_name='desbasteagulhaworker',
            name='die_instance',
        ),
        migrations.RemoveField(
            model_name='desbasteagulhaworker',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='desbastecalibre',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='desbastecalibre',
            name='workers',
        ),
        migrations.RemoveField(
            model_name='desbastecalibreworker',
            name='desbaste_calibre',
        ),
        migrations.RemoveField(
            model_name='desbastecalibreworker',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='polimento',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='polimento',
            name='workers',
        ),
        migrations.RemoveField(
            model_name='polimentoworker',
            name='polimento',
        ),
        migrations.RemoveField(
            model_name='polimentoworker',
            name='worker',
        ),
        migrations.DeleteModel(
            name='Worker',
        ),
        migrations.AddField(
            model_name='dieinstance',
            name='bearing',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='dieinstance',
            name='cone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='die',
            name='die_type',
            field=models.CharField(choices=[('ND', 'ND'), ('PCD', 'PCD'), ('MCD', 'MCD')], max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job',
            field=models.CharField(choices=[('F', 'F'), ('R', 'R'), ('P', 'P'), ('W', 'W'), ('N', 'N')], max_length=1, unique=True),
        ),
        migrations.DeleteModel(
            name='Afinacao',
        ),
        migrations.DeleteModel(
            name='AfinacaoWorker',
        ),
        migrations.DeleteModel(
            name='DesbasteAgulha',
        ),
        migrations.DeleteModel(
            name='DesbasteAgulhaWorker',
        ),
        migrations.DeleteModel(
            name='DesbasteCalibre',
        ),
        migrations.DeleteModel(
            name='DesbasteCalibreWorker',
        ),
        migrations.DeleteModel(
            name='Polimento',
        ),
        migrations.DeleteModel(
            name='PolimentoWorker',
        ),
    ]
