# Generated by Django 5.0.6 on 2025-07-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0027_remove_afinacao_qr_code_remove_afinacao_workers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='whereBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where', models.CharField(choices=[('FIO', 'Fio'), ('PRODUCAO', 'Produção'), ('POLIMENTO', 'Polimento')], default='FIO', max_length=20)),
            ],
        ),
    ]
