# Generated by Django 5.0.6 on 2025-07-16 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0028_wherebox'),
    ]

    operations = [
        migrations.AddField(
            model_name='wherebox',
            name='order_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='where_boxes', to='theme.qrdata'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qrdata',
            name='customer_order_nr',
            field=models.CharField(default='9999', max_length=50, unique=True),
        ),
    ]
