# Generated by Django 5.0.6 on 2025-07-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0029_wherebox_order_number_alter_qrdata_customer_order_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrdata',
            name='customer_order_nr',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
