# Generated by Django 5.0.6 on 2025-07-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0030_alter_qrdata_customer_order_nr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrdata',
            name='customer_order_nr',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='qrdata',
            name='toma_order_nr',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='wherebox',
            name='where',
            field=models.CharField(choices=[('AFINACAO', 'Afinação'), ('POLIMENTO', 'Polimento'), ('DESBASTE_AGULHA', 'Desbaste Agulha'), ('DESBASTE_CALIBRE', 'Desbaste Calibre')], default='FIO', max_length=20),
        ),
    ]
