# Generated by Django 5.0.6 on 2025-07-29 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0032_globallogs'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhereDie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where', models.CharField(choices=[('FIO', 'Fio'), ('PRODUCAO', 'Produção'), ('POLIMENTO', 'Polimento')], default='FIO', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('die', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='theme.dieinstance')),
            ],
        ),
        migrations.DeleteModel(
            name='whereBox',
        ),
    ]
