# Generated by Django 5.0.6 on 2025-07-29 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0033_wheredie_delete_wherebox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheredie',
            name='where',
            field=models.CharField(choices=[('AFINACAO', 'Afinação'), ('POLIMENTO', 'Polimento'), ('DESBASTE_AGULHA', 'Desbaste Agulha'), ('DESBASTE_CALIBRE', 'Desbaste Calibre')], default='FIO', max_length=20),
        ),
        migrations.CreateModel(
            name='whereBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('where', models.CharField(choices=[('AFINACAO', 'Afinação'), ('POLIMENTO', 'Polimento'), ('DESBASTE_AGULHA', 'Desbaste Agulha'), ('DESBASTE_CALIBRE', 'Desbaste Calibre')], default='FIO', max_length=20)),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='where_boxes', to='theme.qrdata')),
            ],
        ),
    ]
