# Generated by Django 5.0.6 on 2025-08-06 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0034_alter_wheredie_where_wherebox'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieinstance',
            name='ano',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='dieinstance',
            name='serial_full',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='qrdata',
            name='toma_order_full',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='dieinstance',
            name='serial_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='qrdata',
            name='toma_order_nr',
            field=models.CharField(max_length=50),
        ),
    ]
