# Generated by Django 5.0.6 on 2025-08-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0035_dieinstance_ano_dieinstance_serial_full_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dieinstance',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='dieinstance',
            name='serial_full',
        ),
        migrations.AlterField(
            model_name='dieinstance',
            name='serial_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
