# Generated by Django 5.0.6 on 2025-08-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0036_remove_dieinstance_ano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosdiametro',
            name='pedido_por',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
