# Generated by Django 5.0.6 on 2025-08-07 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0038_pedidosdiametro_serie_dies'),
    ]

    operations = [
        migrations.AddField(
            model_name='numeropartidos',
            name='serie_dies',
            field=models.TextField(blank=True, null=True),
        ),
    ]
