# Generated by Django 5.0.6 on 2025-08-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0040_rename_serie_dies_numeropartidos_serie_dies_partidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosdiametro',
            name='checkbox',
            field=models.BooleanField(default=False),
        ),
    ]
