# Generated by Django 5.0.6 on 2025-08-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0041_pedidosdiametro_checkbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='numeropartidos',
            name='checkbox',
            field=models.BooleanField(default=False, verbose_name='Feito'),
        ),
        migrations.AlterField(
            model_name='pedidosdiametro',
            name='checkbox',
            field=models.BooleanField(default=False, verbose_name='Feito'),
        ),
    ]
