# Generated by Django 5.0.6 on 2025-08-13 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0042_numeropartidos_checkbox_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliveryDate', models.DateField(blank=True, null=True)),
                ('deliveryType', models.CharField(blank=True, max_length=50, null=True)),
                ('costumer', models.CharField(blank=True, max_length=100, null=True)),
                ('deliveryEntity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theme.deliveryentity', to_field='name')),
                ('identificator', models.ForeignKey(blank=True, db_column='identificator', null=True, on_delete=django.db.models.deletion.CASCADE, to='theme.qrdata', to_field='toma_order_full')),
            ],
        ),
    ]
