# Generated by Django 5.0.6 on 2025-08-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0044_deliverytype_alter_deliveryinfo_deliverytype'),
    ]

    operations = [
        migrations.AddField(
            model_name='numeropartidos',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidosdiametro',
            name='observations',
            field=models.TextField(blank=True, null=True),
        ),
    ]
