# Generated by Django 5.0.6 on 2025-08-20 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0045_numeropartidos_observations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=20, unique=True)),
                ('orders_coming', models.CharField(blank=True, max_length=100, null=True)),
                ('courier', models.CharField(blank=True, choices=[('DHL', 'DHL'), ('UPS', 'UPS'), ('FedEx', 'FedEx'), ('SCHENKER', 'SCHENKER'), ('TNT', 'TNT')], max_length=100, null=True)),
                ('shipping_date', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='order_files/')),
            ],
        ),
    ]
