# Generated by Django 5.0.6 on 2025-08-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0047_remove_order_files_orderfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfile',
            name='restricted',
            field=models.BooleanField(default=False),
        ),
    ]
