# Generated by Django 5.0.6 on 2025-08-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0048_orderfile_restricted'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='inspectionMetrology',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='mark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
    ]
