# Generated by Django 5.0.6 on 2025-08-21 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0049_order_done_order_inspectionmetrology_order_mark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersComing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=100)),
                ('inspectionMetrology', models.BooleanField(default=False)),
                ('mark', models.BooleanField(default=False)),
                ('urgent', models.BooleanField(default=False)),
                ('done', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='done',
        ),
        migrations.RemoveField(
            model_name='order',
            name='inspectionMetrology',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='order',
            name='urgent',
        ),
        migrations.AlterField(
            model_name='order',
            name='orders_coming',
            field=models.ForeignKey(default=5.788328387734916, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='theme.orderscoming'),
            preserve_default=False,
        ),
    ]
