# Generated by Django 5.0.6 on 2025-08-21 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0050_orderscoming_remove_order_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='orders_coming',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='inspectionMetrology',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='mark',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='OrdersComing',
        ),
    ]
