# Generated by Django 5.0.6 on 2025-08-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0052_orderscoming_remove_order_done_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orders_coming',
        ),
        migrations.AddField(
            model_name='order',
            name='orders_coming',
            field=models.ManyToManyField(blank=True, related_name='orders', to='theme.orderscoming'),
        ),
    ]
