# Generated by Django 5.0.6 on 2025-08-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0053_remove_order_orders_coming_order_orders_coming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderscoming',
            name='order',
            field=models.CharField(max_length=500),
        ),
    ]
