# Generated by Django 5.2.5 on 2025-08-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0054_alter_orderscoming_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='plant',
            field=models.CharField(blank=True, choices=[('P2', 'P2'), ('P3', 'P3')], max_length=2, null=True),
        ),
    ]
