# Generated by Django 5.2.5 on 2025-09-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0054_alter_orderscoming_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='arriving_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='plant',
            field=models.CharField(blank=True, choices=[('P2', 'P2'), ('P3', 'P3'), ('Toma', 'Toma')], max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='orderscoming',
            name='data_done',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderscoming',
            name='preshipment',
            field=models.BooleanField(default=False),
        ),
    ]
