# Generated by Django 5.2.5 on 2025-09-04 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0056_orderscoming_preshipment_alter_order_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='arriving_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
