# Generated by Django 5.2.5 on 2025-09-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0057_order_arriving_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderscoming',
            name='data_done',
            field=models.DateField(blank=True, null=True),
        ),
    ]
