# Generated by Django 5.2.6 on 2025-09-10 12:17

import django.db.models.deletion
import theme.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0058_orderscoming_data_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dieinstance',
            name='bearing',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dieinstance',
            name='cone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job',
            field=models.CharField(choices=[('F', 'Final(F)'), ('R', 'Recondicionado(R)'), ('P', 'Polir(P)'), ('W', 'Com o mesmo diametro(W)'), ('N', 'Novo(N)')], max_length=1, unique=True),
        ),
        migrations.AlterField(
            model_name='qrdata',
            name='customer_order_nr',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='qrdata',
            name='tolerance',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='theme.tolerance'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tolerance',
            name='max',
            field=theme.models.FlexibleDecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='tolerance',
            name='min',
            field=theme.models.FlexibleDecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
    ]
