# Generated by Django 5.2.6 on 2025-09-10 15:25

import theme.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0059_dieinstance_bearing_is_red_alter_dieinstance_bearing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrdata',
            name='tolerance',
        ),

        migrations.AlterField(
            model_name='tolerance',
            name='max',
            field=theme.models.FlexibleDecimalField(decimal_places=4, default=(0.1000), max_digits=6),
            preserve_default=False,
        ),
    ]
