# Generated by Django 5.2.6 on 2025-09-10 15:26

import theme.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0060_remove_qrdata_tolerance_dieinstance_bearing_is_red_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tolerance',
            name='max',
            field=theme.models.FlexibleDecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
    ]
