# Generated by Django 5.2.6 on 2025-09-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0061_alter_tolerance_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieinstance',
            name='bearing_is_red',
            field=models.BooleanField(default=False),
        ),
    ]
