# Generated by Django 5.2.6 on 2025-09-11 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0062_dieinstance_bearing_is_red'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('finalidade', models.CharField(choices=[('Importacao', 'Importação'), ('Exportacao', 'Exportação')], max_length=20)),
                ('crm', models.CharField(max_length=100)),
                ('destinatario', models.CharField(max_length=100)),
                ('transportadora', models.CharField(choices=[('DHL', 'DHL'), ('UPS', 'UPS'), ('FedEx', 'FedEx'), ('SCHENKER', 'SCHENKER'), ('TNT', 'TNT'), ('NACEX', 'NACEX'), ('Outros', 'Outros')], max_length=20)),
                ('carta_de_porte', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_recolha', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='tracking_files/')),
            ],
        ),
    ]
