# Generated by Django 5.2.6 on 2025-09-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0063_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tracking_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tracking',
            name='files',
        ),
        migrations.AddField(
            model_name='tracking',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='trackings', to='theme.trackingfile'),
        ),
    ]
