# Generated by Django 5.2.6 on 2025-09-12 11:05

import theme.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0064_trackingfile_remove_tracking_files_tracking_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diameters',
            name='max',
            field=theme.models.FlexibleDecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='diameters',
            name='min',
            field=theme.models.FlexibleDecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
    ]
