# Generated by Django 5.2.6 on 2025-09-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0065_alter_diameters_max_alter_diameters_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='plant',
            field=models.CharField(blank=True, choices=[('P2', 'P2'), ('P3', 'P3'), ('Toma', 'Toma'), ('Spider Extrusion', 'Spider Extrusion'), ('Paganoni', 'Paganoni'), ('Outros', 'Outros')], max_length=30, null=True),
        ),
    ]
