# Generated by Django 5.2.6 on 2025-09-23 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0066_alter_order_plant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracking',
            old_name='estado',
            new_name='recebido_por',
        ),
        migrations.AddField(
            model_name='tracking',
            name='data_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tracking',
            name='remetente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tracking',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
