# Generated by Django 5.2.6 on 2025-09-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0067_rename_estado_tracking_recebido_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='exportado',
            field=models.BooleanField(default=False),
        ),
    ]
