# Generated by Django 5.2.6 on 2025-09-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0068_order_exportado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='destinatario',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
