# Generated by Django 5.2.6 on 2025-09-29 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0069_alter_tracking_destinatario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracking',
            old_name='destinatario',
            new_name='cliente',
        ),
        migrations.RemoveField(
            model_name='tracking',
            name='remetente',
        ),
    ]
