# Generated by Django 5.2.6 on 2025-10-08 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0070_rename_destinatario_tracking_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrdata',
            name='envio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qrdata',
            name='production_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
