# Generated by Django 5.2.6 on 2025-10-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0071_qrdata_envio_qrdata_production_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrdata',
            name='envio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='qrdata',
            name='production_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
