# Generated by Django 5.2.6 on 2025-10-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0072_alter_qrdata_envio_alter_qrdata_production_start'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoFieira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=20, unique=True)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('diametro_atual', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('angulo', models.CharField(blank=True, max_length=30, null=True)),
                ('po', models.CharField(blank=True, max_length=30, null=True)),
                ('tempo', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='wherebox',
            name='where',
            field=models.CharField(choices=[('AFINACAO', 'Afinação'), ('POLIMENTO', 'Polimento'), ('DESBASTE_AGULHA', 'Desbaste Agulha'), ('DESBASTE_CALIBRE', 'Desbaste Calibre'), ('INSPEÇÃO_FINAL', 'Inspeção Final')], default='FIO', max_length=20),
        ),
    ]
