# Generated by Django 5.2.6 on 2025-10-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0073_infofieira_alter_wherebox_where'),
    ]

    operations = [
        migrations.AddField(
            model_name='infofieira',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infofieira',
            name='quando',
            field=models.DateField(blank=True, null=True),
        ),
    ]
