# Generated by Django 5.2.6 on 2025-10-10 10:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0075_infofieira_utilizador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infofieira',
            name='quando',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
