# Generated by Django 5.2.6 on 2025-10-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0076_alter_infofieira_quando'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infofieira',
            name='serial_number',
            field=models.CharField(max_length=20),
        ),
    ]
