# Generated by Django 5.2.6 on 2025-10-10 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0077_alter_infofieira_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheredie',
            name='die',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='theme.dieinstance'),
        ),
        migrations.AlterField(
            model_name='wheredie',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='wheredie',
            name='where',
            field=models.CharField(choices=[('AFINACAO', 'Afinação'), ('POLIMENTO', 'Polimento'), ('DESBASTE_AGULHA', 'Desbaste Agulha'), ('DESBASTE_CALIBRE', 'Desbaste Calibre')], max_length=20),
        ),
    ]
