# Generated by Django 5.2.6 on 2025-11-06 12:33

import django.db.models.deletion
import django.utils.timezone
import theme.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0078_alter_wheredie_die_alter_wheredie_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedidasMaquinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter', theme.models.FlexibleDecimalField(decimal_places=4, max_digits=6)),
                ('ovality', theme.models.FlexibleDecimalField(decimal_places=4, max_digits=6)),
                ('bearing', models.CharField(blank=True, max_length=100, null=True)),
                ('tolerance_min', theme.models.FlexibleDecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('tolerance_max', theme.models.FlexibleDecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('machine_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='theme.maquinas')),
            ],
        ),
    ]
