# Generated by Django 5.2.6 on 2025-11-06 15:03

import theme.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0079_maquinas_medidasmaquinas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medidasmaquinas',
            name='ovality',
            field=theme.models.FlexibleDecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
    ]
