# Generated by Django 5.2.6 on 2025-11-06 15:21

import django.db.models.deletion
import django.utils.timezone
import theme.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0080_alter_medidasmaquinas_ovality'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medidasmaquinas',
            name='bearing',
        ),
        migrations.RemoveField(
            model_name='medidasmaquinas',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='medidasmaquinas',
            name='machine_name',
        ),
        migrations.RemoveField(
            model_name='medidasmaquinas',
            name='ovality',
        ),
        migrations.RemoveField(
            model_name='medidasmaquinas',
            name='tolerance_max',
        ),
        migrations.RemoveField(
            model_name='medidasmaquinas',
            name='tolerance_min',
        ),
        migrations.AddField(
            model_name='medidasmaquinas',
            name='serie_number',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Medicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('diameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes', to='theme.medidasmaquinas')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes', to='theme.maquinas')),
            ],
        ),
        migrations.CreateModel(
            name='DetalhesMedicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_number', models.IntegerField()),
                ('diameter', theme.models.FlexibleDecimalField(decimal_places=4, max_digits=6)),
                ('bearing', models.CharField(blank=True, max_length=100, null=True)),
                ('ovality', theme.models.FlexibleDecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('medicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalhes', to='theme.medicao')),
            ],
        ),
    ]
