# Generated by Django 5.2.6 on 2025-11-07 10:34

import theme.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0081_remove_medidasmaquinas_bearing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalhesmedicao',
            name='toleranciaMax',
            field=theme.models.FlexibleDecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='detalhesmedicao',
            name='toleranciaMin',
            field=theme.models.FlexibleDecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
    ]
