# Generated by Django 5.2.6 on 2025-11-26 11:26

import django.db.models.deletion
import django.utils.timezone
import theme.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0082_detalhesmedicao_toleranciamax_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalibracaoMaquina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diam_original', theme.models.FlexibleDecimalField(decimal_places=4, max_digits=6)),
                ('diam_calibrado', theme.models.FlexibleDecimalField(decimal_places=4, max_digits=6)),
                ('diam_calibrado_max', theme.models.FlexibleDecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('diam_calibrado_min', theme.models.FlexibleDecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('details', models.TextField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calibracoes', to='theme.maquinas')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
