# Generated by Django 5.2.6 on 2025-12-02 09:39

import theme.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0083_calibracaomaquina'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieworkworker',
            name='diam_max',
            field=theme.models.FlexibleDecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='dieworkworker',
            name='diam_min',
            field=theme.models.FlexibleDecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
    ]
