# Generated by Django 5.2.6 on 2025-12-03 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0084_dieworkworker_diam_max_dieworkworker_diam_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieinstance',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='theme.wheredie'),
        ),
    ]
