# Generated by Django 5.2.6 on 2025-12-11 12:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0085_dieinstance_local'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dieinstance',
            name='local',
        ),
        migrations.AlterField(
            model_name='diework',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='dieworkworker',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
