# Generated by Django 5.2.6 on 2025-12-17 11:30

import django.db.models.deletion
import theme.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0086_remove_dieinstance_local_alter_diework_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='tracking',
            name='enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', theme.models.FlexibleDecimalField(decimal_places=2, max_digits=10)),
                ('em_estoque', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_relacionados', to='theme.categoria')),
            ],
        ),
    ]
