# Generated by Django 5.2.6 on 2025-12-17 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0087_categoria_tracking_enviado_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
