# Generated by Django 5.2.6 on 2025-12-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0088_remove_produto_categoria_delete_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wherebox',
            name='where',
            field=models.CharField(choices=[('AFINACAO', 'Afinação'), ('POLIMENTO', 'Polimento'), ('DESBASTE_AGULHA', 'Desbaste Agulha'), ('DESBASTE_CALIBRE', 'Desbaste Calibre'), ('INSPEÇÃO_FINAL', 'Inspeção Final'), ('METROLOGY', 'Metrology'), ('FECHADO', 'Fechado')], default='FIO', max_length=20),
        ),
        migrations.AlterField(
            model_name='wheredie',
            name='where',
            field=models.CharField(choices=[('AFINACAO', 'Afinação'), ('POLIMENTO', 'Polimento'), ('DESBASTE_AGULHA', 'Desbaste Agulha'), ('DESBASTE_CALIBRE', 'Desbaste Calibre'), ('INSPEÇÃO_FINAL', 'Inspeção Final'), ('METROLOGY', 'Metrology'), ('FECHADO', 'Fechado')], max_length=20),
        ),
    ]
