# Generated by Django 5.2.6 on 2026-01-07 09:51

import django.db.models.deletion
import theme.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0089_alter_wherebox_where_alter_wheredie_where'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosdiametro',
            name='diametro_min',
            field=theme.models.FlexibleDecimalField(decimal_places=4, default=(0.000), max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qrdata',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedidosdiametro',
            name='observations',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidosdiametro',
            name='pedido_por',
            field=models.TextField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pedidosdiametro',
            name='serie_dies',
            field=models.TextField(),
        ),
    ]
