# Generated by Django 5.2.6 on 2026-01-07 11:43

import theme.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0091_numeropartidos_criado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dieworkworker',
            name='diam_max',
            field=theme.models.FlexibleDecimalField(decimal_places=4, default=0.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dieworkworker',
            name='diam_min',
            field=theme.models.FlexibleDecimalField(decimal_places=4, default=0.0001, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='numeropartidos',
            name='observations',
            field=models.TextField(default='KAPUT4 DI ISTOIRO OH MOCO'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='qrdata',
            name='customer_order_nr',
            field=models.CharField(default='n definido', max_length=50),
            preserve_default=False,
        ),
    ]
