# Generated by Django 5.2.6 on 2026-01-09 10:46

import theme.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0092_alter_dieworkworker_diam_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosdiametro',
            name='diametro_inicial',
            field=theme.models.FlexibleDecimalField(decimal_places=4, default=0.0101, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidosdiametro',
            name='novo_diametro',
            field=theme.models.FlexibleDecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='pedidosdiametro',
            name='trabalhado',
            field=models.BooleanField(default=False, verbose_name='Trabalhado'),
        ),
        migrations.AlterField(
            model_name='pedidosdiametro',
            name='observations',
            field=models.CharField(choices=[('buraco_no_cone', 'Buraco no Cone'), ('buraco_no_calibre', 'Buraco no Calibre'), ('riscos_cone', 'Riscos no Cone'), ('riscos_calibre', 'Riscos no Calibre'), ('margem', 'Margem'), ('outros', 'Outros')], default='buraco_no_cone', max_length=50),
        ),
    ]
