# Generated by Django 5.2.6 on 2026-01-09 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0093_pedidosdiametro_diametro_inicial_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidosdiametro',
            name='diametro_inicial',
        ),
    ]
