# Generated by Django 5.2.6 on 2026-01-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0094_remove_pedidosdiametro_diametro_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosdiametro',
            name='descricao_pormenorizada',
            field=models.TextField(blank=True, null=True),
        ),
    ]
