# Generated by Django 5.2.6 on 2026-01-09 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0095_pedidosdiametro_descricao_pormenorizada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidosdiametro',
            name='descricao_pormenorizada',
        ),
    ]
