# Generated by Django 5.2.6 on 2026-01-16 09:52

import theme.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0096_remove_pedidosdiametro_descricao_pormenorizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieinstance',
            name='new_diameter',
            field=theme.models.FlexibleDecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
    ]
