# Generated by Django 5.2.6 on 2026-01-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0097_dieinstance_new_diameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dieinstance',
            name='new_diameter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pedidosdiametro',
            name='novo_diametro',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
