# Generated by Django 5.2.6 on 2026-01-29 11:01

import django.db.models.deletion
import django.utils.timezone
import theme.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0098_alter_dieinstance_new_diameter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('debito_direto', models.BooleanField(default=False)),
                ('email', models.TextField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('vat', models.CharField(blank=True, max_length=50, null=True)),
                ('morada', models.TextField(blank=True, null=True)),
                ('estrangeiro', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='faturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fatura_unica', models.CharField(max_length=100, unique=True)),
                ('numero_fatura', models.CharField(max_length=100)),
                ('data_fatura', models.DateField()),
                ('valor', theme.models.FlexibleDecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ficheiros', models.FileField(blank=True, null=True, upload_to='faturas_files/')),
                ('ficheiros_estrangeiro', models.FileField(blank=True, null=True, upload_to='faturas_files_estrangeiro/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='theme.fornecedor')),
            ],
        ),
    ]
