# Generated by Django 5.2.6 on 2026-01-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0099_fornecedor_faturas'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturas',
            name='ficheiro_pago',
            field=models.FileField(blank=True, null=True, upload_to='faturas_files_pago/'),
        ),
        migrations.AddField(
            model_name='faturas',
            name='pago',
            field=models.BooleanField(default=False),
        ),
    ]
