# Generated by Django 5.2.6 on 2026-01-29 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0100_faturas_ficheiro_pago_faturas_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faturas',
            name='ficheiro_pago',
        ),
        migrations.RemoveField(
            model_name='faturas',
            name='ficheiros',
        ),
        migrations.RemoveField(
            model_name='faturas',
            name='ficheiros_estrangeiro',
        ),
        migrations.CreateModel(
            name='FaturaEstrangeitoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='faturas_files_estrangeiro/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ficheiros_estrangeiro', to='theme.faturas')),
            ],
        ),
        migrations.CreateModel(
            name='FaturaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='faturas_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ficheiros', to='theme.faturas')),
            ],
        ),
        migrations.CreateModel(
            name='FaturaPagoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='faturas_files_pago/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ficheiros_pago', to='theme.faturas')),
            ],
        ),
    ]
