# Generated by Django 5.2.6 on 2026-01-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0101_remove_faturas_ficheiro_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturas',
            name='data_emissao',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
    ]
