# Generated by Django 5.2.6 on 2026-02-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0102_faturas_data_emissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrdata',
            name='box_nr',
            field=models.CharField(max_length=10),
        ),
    ]
