# Generated by Django 5.2.6 on 2026-02-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0103_alter_qrdata_box_nr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dieinstance',
            name='diam_desbastado',
        ),
        migrations.AddField(
            model_name='dieinstance',
            name='partida',
            field=models.BooleanField(default=False),
        ),
    ]
