# Generated by Django 5.2.6 on 2026-02-06 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0104_remove_dieinstance_diam_desbastado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturas',
            name='data_fatura',
            field=models.DateField(blank=True, null=True),
        ),
    ]
