# Generated by Django 5.2.6 on 2026-02-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0105_alter_faturas_data_fatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='dados_bancarios',
            field=models.TextField(blank=True, null=True),
        ),
    ]
