# Generated by Django 5.2.6 on 2026-02-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0107_template_templatefiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='template',
            name='approved_file',
            field=models.FileField(blank=True, null=True, upload_to='approved_templates_files/'),
        ),
    ]
