# Generated by Django 5.2.6 on 2026-02-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0108_template_approved_template_approved_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderscoming',
            name='casing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderscoming',
            name='days_2_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderscoming',
            name='days_3_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderscoming',
            name='recondicioning',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderscoming',
            name='semifinished',
            field=models.BooleanField(default=False),
        ),
    ]
