# Generated by Django 5.2.6 on 2026-02-19 12:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0109_orderscoming_casing_orderscoming_days_2_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='template',
            name='last_updated',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
