# Generated by Django 5.2.6 on 2026-02-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0110_alter_template_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='approved_by',
            field=models.CharField(default='aniceta', max_length=20),
            preserve_default=False,
        ),
    ]
