# Generated by Django 5.2.6 on 2026-02-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0111_template_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='approved_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
