# Generated by Django 5.2.6 on 2026-02-19 12:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0112_alter_template_approved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='template',
            name='last_updated',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
