# Generated by Django 5.2.6 on 2026-02-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0113_alter_template_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieinstance',
            name='observations_prod',
            field=models.TextField(blank=True, null=True),
        ),
    ]
