# Generated by Django 5.2.6 on 2026-03-04 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0114_dieinstance_observations_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderscoming',
            name='pin',
            field=models.BooleanField(default=False),
        ),
    ]
