# Generated by Django 5.2.6 on 2026-03-10 11:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0115_orderscoming_pin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='qrdata',
            name='observations_prod',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pedidosdiametro',
            name='observations',
            field=models.CharField(choices=[('buraco_no_cone', 'Buraco no Cone'), ('buraco_no_calibre', 'Buraco no Calibre'), ('riscos_cone', 'Raias no Cone'), ('riscos_calibre', 'Raias no Calibre'), ('cortes', 'Cortes'), ('margem', 'Margem'), ('outros', 'Outros')], default='buraco_no_cone', max_length=50),
        ),
        migrations.CreateModel(
            name='Polimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_fieiras', models.IntegerField()),
                ('tipo', models.CharField(choices=[('polimentoE', 'Polimento Entrada'), ('polimentoS', 'Polimento Saida'), ('polimentoC', 'Polimento Cone')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('observations', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
