# Generated by Django 5.2.6 on 2026-03-11 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0116_qrdata_observations_prod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='polimentos',
            name='cliente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
