# Generated by Django 5.2.6 on 2026-03-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0117_polimentos_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderscoming',
            name='conoptica',
            field=models.BooleanField(default=False),
        ),
    ]
