# Generated by Django 5.2.6 on 2026-04-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0118_orderscoming_conoptica'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturas',
            name='moeda',
            field=models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dólar Americano'), ('GBP', 'Libras')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
