# Generated by Django 5.2.6 on 2026-04-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0119_faturas_moeda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='plant',
            field=models.CharField(blank=True, choices=[('P2', 'P2'), ('P3', 'P3'), ('Toma', 'Toma'), ('Spider Extrusion', 'Spider Extrusion'), ('Paganoni', 'Paganoni'), ('3BetterDiamond', '3BetterDiamond'), ('Outros', 'Outros')], max_length=30, null=True),
        ),
    ]
