# Generated by Django 5.2.6 on 2026-05-05 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0122_auto_20260505_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='plant',
        ),
    ]
