# Generated by Django 5.2.6 on 2026-05-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0123_remove_order_plant'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieinstance',
            name='modified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='qrdata',
            name='inspected_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
