# Generated by Django 5.2.6 on 2026-05-13 16:31

import theme.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0124_dieinstance_modified_by_qrdata_inspected_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibracaomaquina',
            name='diam_original',
            field=theme.models.DiameterDecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='detalhesmedicao',
            name='diameter',
            field=theme.models.DiameterDecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='diameters',
            name='max',
            field=theme.models.DiameterDecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='diameters',
            name='min',
            field=theme.models.DiameterDecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='dieinstance',
            name='diam_requerido',
            field=theme.models.DiameterDecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='infofieira',
            name='diametro_atual',
            field=theme.models.DiameterDecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='medidasmaquinas',
            name='diameter',
            field=theme.models.DiameterDecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pedidosdiametro',
            name='diametro',
            field=theme.models.DiameterDecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='pedidosdiametro',
            name='diametro_min',
            field=theme.models.DiameterDecimalField(decimal_places=4, max_digits=6),
        ),
    ]
