# Generated by Django 5.2.6 on 2026-05-13 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0125_alter_calibracaomaquina_diam_original_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieinstance',
            name='fieira_final',
            field=models.BooleanField(default=False),
        ),
    ]
