# Generated by Django 5.2.6 on 2026-05-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0126_dieinstance_fieira_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dieinstance',
            name='fieira_final',
            field=models.BooleanField(default=False),
        ),
    ]
