# Generated by Django 5.2.6 on 2026-05-26 11:51

import theme.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0128_convert_fieira_final_to_boolean'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieworkworker',
            name='diam_desbastado',
            field=theme.models.DiameterDecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='dieworkworker',
            name='diam_max',
            field=theme.models.DiameterDecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='dieworkworker',
            name='diam_min',
            field=theme.models.DiameterDecimalField(decimal_places=4, max_digits=6),
        ),
    ]
