# Generated by Django 5.2.6 on 2026-05-26 13:41

import theme.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0129_dieworkworker_diam_desbastado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dieworkworker',
            name='diam_desbastado',
        ),
        migrations.RemoveField(
            model_name='dieworkworker',
            name='diam_max',
        ),
        migrations.RemoveField(
            model_name='dieworkworker',
            name='diam_min',
        ),
        migrations.AddField(
            model_name='dieinstance',
            name='diam_desbastado',
            field=theme.models.DiameterDecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='dieinstance',
            name='diam_max',
            field=theme.models.DiameterDecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='dieinstance',
            name='diam_min',
            field=theme.models.DiameterDecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
    ]
