# Generated by Django 5.2.6 on 2026-05-26 16:40

import django.db.models.deletion
import django.utils.timezone
import theme.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0130_remove_dieworkworker_diam_desbastado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibracaomaquina',
            name='angle',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='calibracaomaquina',
            name='bearing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='calibracaomaquina',
            name='lev_obj',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='calibracaomaquina',
            name='mec_cal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='calibracaomaquina',
            name='ovality',
            field=theme.models.FlexibleDecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.CreateModel(
            name='Lentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tamanho_lente', models.CharField(max_length=100)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('calibreMaquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lentes', to='theme.maquinas')),
            ],
        ),
    ]
