# Generated by Django 5.2.6 on 2026-05-29 11:12

import theme.models
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    
    dependencies = [
        ('theme', '0131_calibracaomaquina_angle_calibracaomaquina_bearing_and_more'),
    ]

    operations = [
        # 1. Converte as vírgulas em pontos no PostgreSQL ANTES de alterar o campo
        migrations.RunSQL(
            sql="UPDATE theme_dieinstance SET diameter_text = REPLACE(diameter_text, ',', '.') WHERE diameter_text IS NOT NULL;",
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            sql="UPDATE theme_dieinstance SET new_diameter = REPLACE(new_diameter, ',', '.') WHERE new_diameter IS NOT NULL;",
            reverse_sql=migrations.RunSQL.noop
        ),

        # 2. Aplica a alteração do tipo de dados (de string para numeric)
        migrations.AlterField(
            model_name='dieinstance',
            name='diameter_text',
            field=theme.models.DiameterDecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='dieinstance',
            name='new_diameter',
            field=theme.models.DiameterDecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
    ]