# Generated by Django 5.2.6 on 2026-06-09 07:34

import theme.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0132_alter_dieinstance_diameter_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dieinstance',
            name='diam_sugerido',
            field=theme.models.DiameterDecimalField(blank=True, decimal_places=4, max_digits=6, null=True),
        ),
    ]
