# Generated by Django 5.2.6 on 2026-06-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0133_dieinstance_diam_sugerido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job',
            field=models.CharField(choices=[('F', 'F'), ('R', 'R'), ('P', 'P'), ('W', 'W'), ('N', 'N')], max_length=1, unique=True),
        ),
    ]
