# Generated by Django 5.2.6 on 2026-06-26 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0134_alter_jobs_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='courier',
            field=models.CharField(choices=[('DHL', 'DHL'), ('UPS', 'UPS'), ('FedEx', 'FedEx'), ('SCHENKER', 'SCHENKER'), ('TNT', 'TNT')], default='DHL', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_date',
            field=models.DateField(default='2026-06-26'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BoxFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='box_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='qrdata',
            name='box_files',
            field=models.ManyToManyField(blank=True, related_name='qrdata', to='theme.boxfiles'),
        ),
    ]
