# Generated by Django 5.2.6 on 2026-06-26 12:36

import django.db.models.deletion
import theme.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0135_alter_order_courier_alter_order_shipping_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calibracaomaquina',
            name='angle',
        ),
        migrations.RemoveField(
            model_name='calibracaomaquina',
            name='bearing',
        ),
        migrations.RemoveField(
            model_name='calibracaomaquina',
            name='diam_calibrado',
        ),
        migrations.RemoveField(
            model_name='calibracaomaquina',
            name='diam_calibrado_max',
        ),
        migrations.RemoveField(
            model_name='calibracaomaquina',
            name='diam_calibrado_min',
        ),
        migrations.RemoveField(
            model_name='calibracaomaquina',
            name='diam_original',
        ),
        migrations.RemoveField(
            model_name='calibracaomaquina',
            name='ovality',
        ),
        migrations.CreateModel(
            name='LenteCalibracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_lente', models.CharField(max_length=50)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=100, null=True)),
                ('calibracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lentes', to='theme.calibracaomaquina')),
            ],
        ),
        migrations.CreateModel(
            name='MedicaoFieira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diam_fast', theme.models.FlexibleDecimalField(decimal_places=4, max_digits=10)),
                ('diam_medio', theme.models.FlexibleDecimalField(decimal_places=4, max_digits=10)),
                ('ovality', theme.models.FlexibleDecimalField(decimal_places=4, max_digits=10)),
                ('bearing', theme.models.FlexibleDecimalField(decimal_places=4, max_digits=10)),
                ('angle', theme.models.FlexibleDecimalField(decimal_places=4, max_digits=10)),
                ('lente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes', to='theme.lentecalibracao')),
            ],
        ),
        migrations.DeleteModel(
            name='Lentes',
        ),
    ]
