# Generated by Django 5.2.6 on 2026-06-26 12:53

import django.db.models.deletion
import django.utils.timezone
import theme.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0136_remove_calibracaomaquina_angle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicaofieira',
            name='lente',
        ),
        migrations.RemoveField(
            model_name='calibracaomaquina',
            name='details',
        ),
        migrations.AddField(
            model_name='calibracaomaquina',
            name='lente_1x',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lente 1X'),
        ),
        migrations.AddField(
            model_name='calibracaomaquina',
            name='lente_3x',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lente 3X'),
        ),
        migrations.AddField(
            model_name='calibracaomaquina',
            name='lente_meio_x',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lente 1/2X'),
        ),
        migrations.AlterField(
            model_name='calibracaomaquina',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='calibracaomaquina',
            name='lev_obj',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='LEVELS Reference Objective'),
        ),
        migrations.AlterField(
            model_name='calibracaomaquina',
            name='mec_cal',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MEC.CAL.MERIT FUNCTION'),
        ),
        migrations.CreateModel(
            name='CalibracaoFieira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=100)),
                ('diam_original', theme.models.FlexibleDecimalField(decimal_places=4, max_digits=10)),
                ('mean_diameter', theme.models.FlexibleDecimalField(decimal_places=4, max_digits=10)),
                ('ovality', models.CharField(max_length=20)),
                ('bearing', models.CharField(max_length=20)),
                ('angle', models.CharField(max_length=20)),
                ('calibracao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicoes', to='theme.calibracaomaquina')),
            ],
        ),
        migrations.DeleteModel(
            name='LenteCalibracao',
        ),
        migrations.DeleteModel(
            name='MedicaoFieira',
        ),
    ]
