# Generated by Django 5.2.6 on 2026-06-30 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0137_remove_medicaofieira_lente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faturas',
            name='data_enviado',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faturas',
            name='enviado',
            field=models.BooleanField(default=False),
        ),
    ]
