# Generated by Django 5.2.6 on 2026-07-02 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0138_faturas_data_enviado_faturas_enviado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='edit_by',
        ),
        migrations.DeleteModel(
            name='ProductDeleteLog',
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
