# Generated by Django 5.2.6 on 2026-07-14 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0139_remove_products_edit_by_delete_productdeletelog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calibracaomaquina',
            name='feito',
            field=models.BooleanField(default=False, verbose_name='Feito'),
        ),
        migrations.AddField(
            model_name='calibracaomaquina',
            name='tempratura',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
