# Generated by Django 5.2.6 on 2026-07-14 14:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0140_calibracaomaquina_feito_calibracaomaquina_tempratura'),
    ]

    operations = [
        migrations.CreateModel(
            name='P2Control',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_PO', models.CharField(max_length=100, unique=True)),
                ('proforma_number', models.CharField(max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percentage_1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('amount_1', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paydate_1', models.DateField(blank=True, null=True)),
                ('percentage_2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('amount_2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paydate_2', models.DateField(blank=True, null=True)),
                ('proof_of_payment_1', models.FileField(blank=True, null=True, upload_to='p2_control_files/')),
                ('proof_of_payment_2', models.FileField(blank=True, null=True, upload_to='p2_control_files/')),
                ('proforma_invoice', models.FileField(blank=True, null=True, upload_to='p2_control_files/')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, unique=True)),
                ('invoice_date', models.DateField()),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('proformas', models.ManyToManyField(blank=True, related_name='invoices', to='theme.p2control')),
            ],
        ),
    ]
