# Generated by Django 5.2.6 on 2026-07-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0142_invoice_invoice_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2control',
            name='proforma',
            field=models.FileField(blank=True, null=True, upload_to='p2_control_files/'),
        ),
    ]
