# Generated by Django 5.2.6 on 2026-07-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0143_p2control_proforma'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2control',
            name='proforma_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
