# Generated by Django 5.2.6 on 2026-07-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0144_p2control_proforma_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='p2control',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
