# Generated by Django 5.2.6 on 2026-08-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0145_p2control_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidosdiametro',
            name='outras_observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
