# Generated by Django 5.2.6 on 2026-08-13 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0146_pedidosdiametro_outras_observacoes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='faturas',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dieinstance',
            name='serial_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='qrdata',
            name='box_nr',
            field=models.IntegerField(),
        ),
    ]
