# Generated by Django 5.2.6 on 2026-08-14 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0147_faturas_created_by_alter_dieinstance_serial_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidosdiametro',
            name='observations',
            field=models.CharField(choices=[('buraco_no_cone', 'Buraco no Cone'), ('buraco_no_calibre', 'Buraco no Calibre'), ('riscos_cone', 'Raias no Cone'), ('riscos_calibre', 'Raias no Calibre'), ('cortes', 'Cortes'), ('margem', 'Margem'), ('pedra_curta', 'Pedra Curta'), ('outros', 'Outros')], default='buraco_no_cone', max_length=50),
        ),
    ]
