# Imagem base
FROM python:3.11-slim

# Variáveis de ambiente para Python
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Diretório de trabalho
WORKDIR /app

# 1. Instalar dependências do sistema e NODE.JS (Necessário para o Tailwind)
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    curl \
    gnupg \
    && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
    && apt-get install -y nodejs \
    && rm -rf /var/lib/apt/lists/*

# 2. Copiar requirements e instalar dependências Python
COPY requirements.txt /app/
RUN pip install --upgrade pip && pip install -r requirements.txt

# 3. Copiar o código do projeto
COPY . /app/

# 4. Instalar dependências do Tailwind (Node)
# O comando 'npm install' deve rodar onde está o package.json do theme
# Ajuste o caminho 'theme/static_src' se o teu for diferente
#RUN cd theme/static_src && npm install && npm run build

# 5. Coletar ficheiros estáticos (Whitenoise)
RUN python manage.py collectstatic --noinput

# Expor a porta
EXPOSE 8000

# Comando para rodar a aplicação (Apontei para productionApp conforme teu settings.py)
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "productionApp.wsgi:application"]