services:
  db:
    image: postgres:16
    container_name: transport_db
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - transport_net   # <--- NOVO
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: transport_web
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
     # - .:/app
     # - ./static:/app/static
      - /share/CE_CACHEDEV1_DATA/transportInfo/transportInfo/media:/app/media
    networks:
      - transport_net   
    restart: unless-stopped

networks:
  transport_net:
    driver: bridge