# Imagem base
FROM python:3.11-slim

# Variáveis de ambiente para Python
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Diretório de trabalho
WORKDIR /app

# 1. Instalar apenas as dependências do sistema necessárias para o Python/Postgres
# (Removemos o Node.js daqui porque já tens o output.css pronto a usar)
RUN apt-get update && apt-get install -y \
    gcc \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# 2. Copiar requirements e instalar dependências Python
COPY requirements.txt /app/
RUN pip install --upgrade pip && pip install -r requirements.txt

# 3. Copiar o código do projeto (Isto vai copiar o teu output.css que já está no NAS)
COPY . /app/

# 4. Coletar ficheiros estáticos (O Django vai pegar no teu output.css automaticamente)
RUN python manage.py collectstatic --noinput

# Expor a porta
EXPOSE 8000

# Comando para rodar a aplicação
CMD ["gunicorn", "--workers", "3", "--threads", "2", "--timeout", "30", "--bind", "0.0.0.0:8000", "--access-logfile", "-", "--error-logfile", "-", "--capture-output", "--log-level", "info", "productionApp.wsgi:application"]