FROM python:3.12-slim
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
WORKDIR /app

RUN apt-get update && apt-get install -y build-essential libpq-dev && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt gunicorn whitenoise dj-database-url django-environ

COPY . .

# compila estáticos (mesmo sem DB)
RUN DJANGO_SETTINGS_MODULE=productionApp.settings_production python manage.py collectstatic --noinput || true

EXPOSE 8000
CMD ["gunicorn", "productionApp.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "3", "--worker-class", "gthread", "--threads", "4"]
